included:
  - MacToDo/Sources
  - MacToDo/Tests
excluded:
  - MacToDo/Sources/Config
  - MacToDo/Resources
  - MacToDo/.build
line_length:
  warning: 140
  error: 200
identifier_name:
  min_length: 2
type_body_length:
  warning: 300
  error: 600
file_length:
  warning: 800
  error: 1500
opt_in_rules:
  - closure_spacing
  - empty_parentheses_with_trailing_closure
  - vertical_parameter_alignment_on_call
reporter: github-actions
